DLauritz\Forum\ContentBundle\Entity\Post:
    type: entity
    table: posts
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        content:
            type: text
        created:
            type: datetime
        modified:
            type: datetime
    manyToOne:
        creator:
            targetEntity: DLauritz\Forum\UserBundle\Entity\User
            inversedBy: posts
            joinColumn:
                name: user_id
                referencedColumnName: id
        thread:
            targetEntity: Thread
            mappedBy: thread
            inversedBy: posts
            joinColumn:
                name: thread_id
                referencedColumnName: id
