DLauritz\Forum\ContentBundle\Entity\Post:
    type: entity
    table: posts
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        content:
            type: text
        created:
            type: datetime
        modified:
            type: datetime
    oneToOne:
        creator:
            targetEntity: DLauritz\Forum\UserBundle\Entity\User
            mappedBy: user_id
            inversedBy: posts
            joinColumn:
                name: user_id
                referencedColumnName: id
    manyToOne:
        thread:
            targetEntity: Thread
            mappedBy: posts
            joinColumn:
                name: thread_id
                referencedColumnName: id
