DLauritz\Forum\ContentBundle\Entity\Thread:
    type: entity
    table: thread
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 100
    oneToMany:
        posts:
            targetEntity: Post
            mappedBy: thread
            inversedBy: post
        permissions:
            targetEntity: Permissions
            mappedBy: thread
    manyToOne:
        forum:
            targetEntity: Forum
            mappedBy: forum
            inversedBy: threads
            joinColumn:
                name: forum_id
                referencedColumnName: id