DLauritz\Forum\UserBundle\Entity\User:
    type: entity
    table: user
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        username:
            type: string
            length: 20
        password:
            type: string
            length: 100
        display_name:
            type: string
            length: 50
        email:
            type: string
            length: 50
    oneToMany:
        posts:
            targetEntity: DLauritz\Forum\ContentBundle\Entity\Post
            mappedBy: creator
