DLauritz\Forum\UserBundle\Entity\User:
    type: entity
    table: user
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        username:
            type: string
            length: 20
        password:
            type: string
            length: 100
        display_name:
            type: string
            length: 50
        email:
            type: string
            length: 50
    oneToMany:
        posts:
            targetEntity: DLauritz\Forum\ContentBundle\Entity\Post
            mappedBy: creator
    manyToMany:
        groups:
            targetEntity: Group
            inversedBy: members
            joinTable:
                name: usergroups
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    group_id:
                        referencedColumnName: id
    properties:
        username:
            - NotBlank: ~
            - Regex: "/^[a-z0-9\-_]+$/i"
        password:
            - NotBlank: { groups: [registration] }
            - MinLength: { limit: 6, groups: [registration] }
        email:
            - Email: ~
