DLauritzForumUserBundle:
    resource: "@DLauritzForumUserBundle/Resources/config/routing.yml"
    prefix:   /

DLauritzForumContentBundle:
    resource: "@DLauritzForumContentBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
