DLauritzForumAdminBundle:
    resource: "@DLauritzForumAdminBundle/Resources/config/routing.yml"
    prefix:   /

DLauritzForumUserBundle:
    resource: "@DLauritzForumUserBundle/Resources/config/routing.yml"
    prefix:   /

DLauritzForumContentBundle:
    resource: "@DLauritzForumContentBundle/Resources/config/routing.yml"
    prefix:   /

# Update this to point to my actual index page
_index:
    pattern:  /
    defaults:
        _controller: DLauritzForumContentBundle:Forum:index
        _format: html

login:
    pattern: /login.{_format}
    defaults:
        _controller: DLauritzForumUserBundle:User:login
        _format: html
    requirements:
        _format: html|json

login_check:
    pattern: /login_check

logout:
    pattern: /logout

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
