
user_profile_view:
    pattern: /user/{username}.{_format}
    defaults:
        _controller: DLauritzForumUserBundle:User:profile
        username: 'self'
        _format: html
    requirements:
        _format: html|json
